#! /bin/csh -f

#Usage: editWM subjectFolder

set bin = /Volumes/moochie/user_data/CamachoCat/5YOP/5yop/fs_scripts
setenv SUBJECTS_DIR /Volumes/moochie/user_data/CamachoCat/5YOP/freesurfer
set sub = $argv[1]


if( -e $SUBJECTS_DIR/$sub ) then        		
	echo 
	echo "found subject"
	echo
	echo "Using "$SUBJECTS_DIR "/" $sub
	echo
		tkmedit $sub brainmask.mgz lh.white -aux wm.mgz -aux-surface rh.white -tcl $bin/tkmedit_WMedit.tcl

else
	echo " Could not find "$sub"."
    exit 1;
endif

echo ""
echo ""
echo "Who's awesome? You're awesome!"
echo ""
echo ""