#! /bin/csh -f
#
# Usage: regenSurfaces subjectFolder


setenv SUBJECTS_DIR /Users/dendrite/Desktop/Jay/freesurfer
	
foreach sub ($argv)	
echo
echo "****************************************************"
echo
echo "            Running autorecon2 for "$sub
echo
echo "****************************************************"

recon-all -s $sub -autorecon2 -parallel -openmp 3

echo
echo
echo	
if ( -e $SUBJECTS_DIR/$sub/scripts/recon-all.done) then
	echo "Cortical surfaces for "$sub" generated successfully!"
else
	echo "ERROR!! Cortical surfaces for "$sub" failed to generate."
endif

echo
echo "****************************************************"
echo
echo "                   Completed "$sub
echo
echo "****************************************************"

end